apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: my-matching-label-rs
  template:
    metadata:
      labels:
        tier: my-matching-label-rs
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3