apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-old
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-old
  template:
    metadata:
      labels:
        app: nginx-old
    spec:
      containers:
        - name: nginx
          image: nginx:1.18.0